[project]
name = "arrow-translator"
version = "0.3.5"
description = "Small Library to extract data using sqlalchemy project to pyarrow (Arrow) RecordBatches"
readme = "README.md"
authors = [
    { name = "Dimos Konstantinos", email = "konstantinos.dimos@themart.gr" }
]
requires-python = ">=3.12"
dependencies = [
    "pyarrow>=25.0.1",
    "sqlalchemy>=2.0.52",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "psycopg[binary]>=3.3.5",
    "sqlalchemy-hana",
    "pyarrow-stubs>=20.0.0.20260819",
    "python-dotenv",
    "oracledb>=26.0.0",
]
